### PR TITLE
Fixes #5 

### LINKED ISSUE #5: [BUG] TTL needs to be sent as a integer.
https://github.com/axians/otm/blob/73144ad0a6110117466bc3a7c22bb9fc3ab10b86/views/index.html#L82

### PR DESCRIPTION
**Pull request by Utbildadninja**
Fixes #5 by converting the expected string to an integer.
Reset to default TTL when encountering reasonable exceptions.
Log exception and reset to default TTL when encountering unexpected exceptions.

### CODE REVIEW

**Comment by gbyx3** [comment]
I think it would be better to just skip the isinstance int on [L283](https://github.com/axians/otm/blob/73144ad0a6110117466bc3a7c22bb9fc3ab10b86/app.py#L283) and cast the ttl value as an integer

**Comment by Utbildadninja** [comment]
> I think it would be better to just skip the isinstance int on [L283](https://github.com/axians/otm/blob/73144ad0a6110117466bc3a7c22bb9fc3ab10b86/app.py#L283) and cast the ttl value as an integer

Agreed, keeping that change. TTL is now cast to int, error forwarded to user if something goes wrong. Combined nested if statements as suggested.

I was thinking, should we handle negative ttl values as well?

**Comment by gbyx3** [comment]
> I was thinking, should we handle negative ttl values as well? 

You could try something like:

```python
try:
    ttl = int(request_body["ttl"])
    if ttl <= 0:
        raise ValueError("The number must be a positive integer.")
except ValueError as e:
    print(e)
```

**Comment by gbyx3** [comment]
Looks good, we try for a Friday merge! 🙏

**Review by gbyx3 — APPROVED** [review]
lgtm

**Pull request merged**
